#!/bin/sh

GITREPOS_ROOT=~/git-repos

helpAndExit () {
  echo "git-repos clone [url|ssh]"
  exit
}

if [ -z ${1+x} ]; then
    helpAndExit
fi

if [ $1 = "clone" ]; then
  if [ -z ${2+x} ]; then
    helpAndExit
  fi
  regex="git@(.*):(.*)\/(.*)\.git"
  domain=`echo $2 | sed -E "s/$regex/\1/g"`
  user=`echo $2 | sed -E "s/$regex/\2/g"`
  repo=`echo $2 | sed -E "s/$regex/\3/g"`
  dir="$GITREPOS_ROOT/$domain/$user/$repo"
  echo "Clone $2 into $dir"

  git clone $2 $dir
fi









